name: flutter_animated_icon_button
description: An animated icon button for Flutter apps.
version: 1.0.0
homepage: https://github.com/RikitoNoto
repository: https://github.com/RikitoNoto/flutter_animated_icon_button

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
